require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./src/models/ProductModel');
const connectDB = require('./src/config/db');

// Raw Ingredients
const rawIngredients = [
    {
        name: 'White Rice',
        description: 'High-quality gluten-free rice suitable for all meals',
        category: 'raw_ingredients',
        price: 5.99,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['rice'],
        stock: 100,
        sku: 'RICE-WHITE-001',
    },
    {
        name: 'Brown Rice',
        description: 'Brown rice rich in fiber and vitamins',
        category: 'raw_ingredients',
        price: 6.99,
        tags: ['gluten-free', 'vegan', 'high-fiber'],
        ingredients: ['brown rice'],
        stock: 80,
        sku: 'RICE-BROWN-002',
    },
    {
        name: 'Corn Flour',
        description: 'Pure corn flour - gluten-free',
        category: 'raw_ingredients',
        price: 4.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['corn'],
        stock: 120,
        sku: 'CORN-FLOUR-003',
    },
    {
        name: 'Frozen Corn',
        description: 'Fresh frozen corn kernels',
        category: 'raw_ingredients',
        price: 3.99,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['corn'],
        stock: 150,
        sku: 'CORN-FROZEN-004',
    },
    {
        name: 'Sweet Potato',
        description: 'Fresh sweet potato rich in vitamins',
        category: 'raw_ingredients',
        price: 2.99,
        tags: ['gluten-free', 'vegan', 'high-fiber'],
        ingredients: ['sweet potato'],
        stock: 100,
        sku: 'POTATO-SWEET-005',
    },
    {
        name: 'Potato Starch',
        description: 'Pure potato starch - great flour alternative',
        category: 'raw_ingredients',
        price: 6.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['potato starch'],
        stock: 75,
        sku: 'POTATO-STARCH-006',
    },
    {
        name: 'Gluten-Free Oats',
        description: '100% certified gluten-free oats',
        category: 'raw_ingredients',
        price: 7.99,
        tags: ['gluten-free', 'vegan', 'high-fiber', 'organic'],
        ingredients: ['oats'],
        stock: 90,
        sku: 'OATS-GF-007',
    },
    {
        name: 'Quinoa',
        description: 'Whole quinoa - complete protein and gluten-free',
        category: 'raw_ingredients',
        price: 9.99,
        tags: ['gluten-free', 'vegan', 'high-protein', 'organic'],
        ingredients: ['quinoa'],
        stock: 60,
        sku: 'QUINOA-008',
    },
    {
        name: 'Amaranth',
        description: 'Whole amaranth grains - high in protein',
        category: 'raw_ingredients',
        price: 8.49,
        tags: ['gluten-free', 'vegan', 'high-protein'],
        ingredients: ['amaranth'],
        stock: 50,
        sku: 'AMARANTH-009',
    },
    {
        name: 'Millet',
        description: 'Whole millet grains - gluten-free',
        category: 'raw_ingredients',
        price: 6.99,
        tags: ['gluten-free', 'vegan', 'high-fiber'],
        ingredients: ['millet'],
        stock: 70,
        sku: 'MILLET-010',
    },
    {
        name: 'Sorghum',
        description: 'Sorghum grains - completely safe for malabsorption patients',
        category: 'raw_ingredients',
        price: 7.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['sorghum'],
        stock: 55,
        sku: 'SORGHUM-011',
    },
    {
        name: 'Red Lentils',
        description: 'Red lentils high in protein and fiber',
        category: 'raw_ingredients',
        price: 4.99,
        tags: ['gluten-free', 'vegan', 'high-protein', 'high-fiber'],
        ingredients: ['red lentils'],
        stock: 110,
        sku: 'LENTILS-RED-012',
    },
    {
        name: 'Black Lentils',
        description: 'Black lentils rich in nutrients',
        category: 'raw_ingredients',
        price: 5.49,
        tags: ['gluten-free', 'vegan', 'high-protein'],
        ingredients: ['black lentils'],
        stock: 95,
        sku: 'LENTILS-BLACK-013',
    },
    {
        name: 'Chickpeas',
        description: 'Whole chickpeas - great source of protein and fiber',
        category: 'raw_ingredients',
        price: 5.99,
        tags: ['gluten-free', 'vegan', 'high-protein', 'high-fiber'],
        ingredients: ['chickpeas'],
        stock: 120,
        sku: 'CHICKPEAS-014',
    },
    {
        name: 'Beans',
        description: 'Healthy beans rich in protein',
        category: 'raw_ingredients',
        price: 4.49,
        tags: ['gluten-free', 'vegan', 'high-protein'],
        ingredients: ['beans'],
        stock: 100,
        sku: 'BEANS-015',
    },
    {
        name: 'Natural Almonds',
        description: '100% natural almonds with no additives',
        category: 'raw_ingredients',
        price: 12.99,
        tags: ['gluten-free', 'vegan', 'high-protein', 'tree-nut'],
        ingredients: ['almonds'],
        stock: 50,
        sku: 'ALMONDS-016',
    },
    {
        name: 'Walnuts',
        description: 'Natural walnuts rich in Omega-3 acids',
        category: 'raw_ingredients',
        price: 13.99,
        tags: ['gluten-free', 'vegan', 'high-protein'],
        ingredients: ['walnuts'],
        stock: 45,
        sku: 'WALNUTS-017',
    },
    {
        name: 'Dried Coconut',
        description: 'Natural dried coconut',
        category: 'raw_ingredients',
        price: 8.99,
        tags: ['gluten-free', 'vegan', 'dairy-free'],
        ingredients: ['coconut'],
        stock: 70,
        sku: 'COCONUT-018',
    },
    {
        name: 'Fresh Carrots',
        description: 'Organic fresh carrots from the farm',
        category: 'raw_ingredients',
        price: 1.99,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['carrot'],
        stock: 150,
        sku: 'CARROT-019',
    },
    {
        name: 'Fresh Broccoli',
        description: 'Fresh organic broccoli',
        category: 'raw_ingredients',
        price: 2.99,
        tags: ['gluten-free', 'vegan', 'organic', 'high-fiber'],
        ingredients: ['broccoli'],
        stock: 100,
        sku: 'BROCCOLI-020',
    },
    {
        name: 'Apples',
        description: 'Fresh organic apples',
        category: 'raw_ingredients',
        price: 2.49,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['apple'],
        stock: 200,
        sku: 'APPLE-021',
    },
    {
        name: 'Bananas',
        description: 'Fresh bananas',
        category: 'raw_ingredients',
        price: 0.99,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['banana'],
        stock: 250,
        sku: 'BANANA-022',
    },
    {
        name: 'Natural Eggs',
        description: 'Fresh eggs from free-range chickens',
        category: 'raw_ingredients',
        price: 3.99,
        tags: ['gluten-free', 'high-protein'],
        ingredients: ['eggs'],
        stock: 200,
        sku: 'EGGS-023',
    },
    {
        name: 'Chicken Breast',
        description: 'Fresh high-quality chicken breast',
        category: 'raw_ingredients',
        price: 6.99,
        tags: ['gluten-free', 'high-protein'],
        ingredients: ['chicken breast'],
        stock: 80,
        sku: 'CHICKEN-024',
    },
    {
        name: 'Salmon Fish',
        description: 'Fresh salmon rich in Omega-3',
        category: 'raw_ingredients',
        price: 14.99,
        tags: ['gluten-free', 'high-protein', 'high-omega3'],
        ingredients: ['salmon'],
        stock: 40,
        sku: 'SALMON-025',
    },
    {
        name: 'Fresh Cow Milk',
        description: 'Fresh milk from free-range cows',
        category: 'raw_ingredients',
        price: 2.99,
        tags: ['gluten-free', 'high-protein'],
        ingredients: ['milk'],
        stock: 100,
        sku: 'MILK-026',
    },
    {
        name: 'Greek Yogurt',
        description: 'Thick Greek yogurt rich in protein',
        category: 'raw_ingredients',
        price: 4.49,
        tags: ['gluten-free', 'high-protein'],
        ingredients: ['yogurt'],
        stock: 90,
        sku: 'YOGURT-027',
    },
];

// Ready-to-Eat Products
const readyProducts = [
    {
        name: 'Gluten-Free Bread',
        description: 'Fresh bread made from rice and corn flour',
        category: 'ready_products',
        price: 4.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['rice flour', 'corn flour', 'water', 'salt', 'yeast'],
        stock: 60,
        sku: 'BREAD-GF-101',
    },
    {
        name: 'Gluten-Free Pasta',
        description: 'Healthy pasta made from corn and rice flour',
        category: 'ready_products',
        price: 3.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['corn flour', 'rice flour', 'water'],
        stock: 80,
        sku: 'PASTA-GF-102',
    },
    {
        name: 'Gluten-Free Biscuits',
        description: 'Crispy and delicious gluten-free biscuits',
        category: 'ready_products',
        price: 2.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['rice flour', 'oil', 'sugar', 'salt'],
        stock: 100,
        sku: 'BISCUITS-GF-103',
    },
    {
        name: 'Gluten-Free Cookies',
        description: 'Delicious gluten-free and egg-free cookies',
        category: 'ready_products',
        price: 3.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['rice flour', 'coconut oil', 'honey'],
        stock: 75,
        sku: 'COOKIES-GF-104',
    },
    {
        name: 'Gluten-Free Cake',
        description: 'Moist and delicious cake made from gluten-free flour',
        category: 'ready_products',
        price: 5.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['rice flour', 'eggs', 'sugar', 'oil'],
        stock: 50,
        sku: 'CAKE-GF-105',
    },
    {
        name: 'Gluten-Free Muffin',
        description: 'Chocolate gluten-free muffin',
        category: 'ready_products',
        price: 2.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['gluten-free flour', 'cocoa', 'eggs', 'oil'],
        stock: 90,
        sku: 'MUFFIN-GF-106',
    },
    {
        name: 'Cornflakes Breakfast Cereal',
        description: 'Crispy corn flakes certified gluten-free',
        category: 'ready_products',
        price: 3.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['corn', 'sugar', 'salt'],
        stock: 120,
        sku: 'CORNFLAKES-107',
    },
    {
        name: 'Gluten-Free Granola',
        description: 'Healthy granola from gluten-free oats and nuts',
        category: 'ready_products',
        price: 6.99,
        tags: ['gluten-free', 'vegan', 'high-fiber'],
        ingredients: ['gluten-free oats', 'nuts', 'honey', 'seeds'],
        stock: 70,
        sku: 'GRANOLA-GF-108',
    },
    {
        name: 'Gluten-Free Granola Bars',
        description: 'Healthy snack bars shaped granola',
        category: 'ready_products',
        price: 1.99,
        tags: ['gluten-free', 'vegan', 'high-fiber'],
        ingredients: ['gluten-free oats', 'honey', 'nuts'],
        stock: 150,
        sku: 'GRANOLA-BAR-109',
    },
    {
        name: 'Gluten-Free Pizza',
        description: 'Pizza with base made from rice and corn flour',
        category: 'ready_products',
        price: 7.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['rice flour', 'corn flour', 'tomato sauce', 'herbs'],
        stock: 40,
        sku: 'PIZZA-GF-110',
    },
    {
        name: 'Natural Tomato Sauce',
        description: 'Tomato sauce free from starch and preservatives',
        category: 'ready_products',
        price: 2.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['tomato', 'herbs', 'salt'],
        stock: 100,
        sku: 'SAUCE-TOMATO-111',
    },
    {
        name: 'Natural Mayonnaise',
        description: 'Gluten-free mayonnaise free from preservatives',
        category: 'ready_products',
        price: 3.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['eggs', 'oil', 'vinegar', 'salt'],
        stock: 80,
        sku: 'MAYO-112',
    },
    {
        name: 'Organic Mustard',
        description: 'Gluten-free mustard free from artificial ingredients',
        category: 'ready_products',
        price: 2.99,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['mustard seeds', 'vinegar', 'salt'],
        stock: 90,
        sku: 'MUSTARD-113',
    },
];

// Beverages
const beverages = [
    {
        name: 'Fresh Orange Juice',
        description: '100% fresh orange juice with no added sugar',
        category: 'beverages',
        price: 3.99,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['orange juice'],
        stock: 80,
        sku: 'JUICE-ORANGE-201',
    },
    {
        name: 'Fresh Apple Juice',
        description: '100% organic fresh apple juice',
        category: 'beverages',
        price: 3.49,
        tags: ['gluten-free', 'vegan', 'organic'],
        ingredients: ['apple juice'],
        stock: 90,
        sku: 'JUICE-APPLE-202',
    },
    {
        name: 'Fresh Carrot Juice',
        description: 'Carrot juice rich in vitamins',
        category: 'beverages',
        price: 2.99,
        tags: ['gluten-free', 'vegan', 'organic', 'high-fiber'],
        ingredients: ['carrot juice'],
        stock: 70,
        sku: 'JUICE-CARROT-203',
    },
    {
        name: 'Natural Roasted Coffee',
        description: 'Naturally roasted coffee free from additives',
        category: 'beverages',
        price: 8.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['coffee beans'],
        stock: 60,
        sku: 'COFFEE-NATURAL-204',
    },
    {
        name: 'Black Tea',
        description: 'Premium black tea from finest estates',
        category: 'beverages',
        price: 5.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['black tea'],
        stock: 50,
        sku: 'TEA-BLACK-205',
    },
    {
        name: 'Green Tea',
        description: 'Natural green tea with great health benefits',
        category: 'beverages',
        price: 6.49,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['green tea'],
        stock: 55,
        sku: 'TEA-GREEN-206',
    },
    {
        name: 'Fresh Cow Milk',
        description: 'Fresh milk from free-range cows',
        category: 'beverages',
        price: 2.99,
        tags: ['gluten-free', 'high-protein'],
        ingredients: ['milk'],
        stock: 100,
        sku: 'MILK-FRESH-207',
    },
    {
        name: 'Almond Milk',
        description: 'Natural almond milk with no added sugar',
        category: 'beverages',
        price: 4.49,
        tags: ['gluten-free', 'vegan', 'dairy-free'],
        ingredients: ['almonds', 'water'],
        stock: 70,
        sku: 'MILK-ALMOND-208',
    },
    {
        name: 'Coconut Milk',
        description: 'Organic coconut milk',
        category: 'beverages',
        price: 4.99,
        tags: ['gluten-free', 'vegan', 'dairy-free'],
        ingredients: ['coconut', 'water'],
        stock: 75,
        sku: 'MILK-COCONUT-209',
    },
    {
        name: 'Gluten-Free Oat Milk',
        description: '100% certified gluten-free oat milk',
        category: 'beverages',
        price: 4.29,
        tags: ['gluten-free', 'vegan', 'dairy-free', 'high-fiber'],
        ingredients: ['gluten-free oats', 'water'],
        stock: 80,
        sku: 'MILK-OATS-GF-210',
    },
    {
        name: 'Soda - Cola',
        description: 'Soft drink gluten-free',
        category: 'beverages',
        price: 1.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['cola'],
        stock: 150,
        sku: 'SODA-COLA-211',
    },
    {
        name: 'Soda - Sprite',
        description: 'Lemon-flavored soft drink gluten-free',
        category: 'beverages',
        price: 1.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['sprite'],
        stock: 140,
        sku: 'SODA-SPRITE-212',
    },
    {
        name: 'Sparkling Water',
        description: 'Natural sparkling water with no additives',
        category: 'beverages',
        price: 0.99,
        tags: ['gluten-free', 'vegan'],
        ingredients: ['sparkling water'],
        stock: 200,
        sku: 'SPARKLING-WATER-213',
    },
];

const seedDatabase = async () => {
    try {
        console.log('🌱 Starting database seeding...\n');

        // Clear existing products
        await Product.deleteMany({});
        console.log('✅ Cleared existing products');

        // Insert all products
        const allProducts = [...rawIngredients, ...readyProducts, ...beverages];
        const result = await Product.insertMany(allProducts);

        console.log(`✅ Successfully inserted ${result.length} products into database\n`);
        console.log(`   📦 Raw Ingredients: ${rawIngredients.length}`);
        console.log(`   🍱 Ready Products: ${readyProducts.length}`);
        console.log(`   🥤 Beverages: ${beverages.length}`);

        // Show some statistics
        const categories = await Product.aggregate([
            { $group: { _id: '$category', count: { $sum: 1 } } },
        ]);

        console.log('\n📊 Products by category:');
        categories.forEach((cat) => {
            const catName = {
                raw_ingredients: 'Raw Ingredients',
                ready_products: 'Ready-to-Eat Products',
                beverages: 'Beverages',
            };
            console.log(`   ${catName[cat._id] || cat._id}: ${cat.count}`);
        });

        console.log('\n✨ Database seeding completed successfully!');
        process.exit(0);
    } catch (error) {
        console.error('❌ Error seeding database:', error);
        process.exit(1);
    }
};



// Run seeding
connectDB().then(() => {
    seedDatabase();
});
